import { Gameweek } from "types/gameweek";
import { Player } from "types/player";

export const mockGameweek: Gameweek = {
  average_entry_score: 10,
  chip_plays: [],
  cup_leagues_created: true,
  data_checked: false,
  deadline_time: new Date("2022-02-08T18:15:00Z"),
  deadline_time_epoch: 1644344100,
  deadline_time_game_offset: 0,
  finished: false,
  h2h_ko_matches_created: true,
  highest_score: 73,
  highest_scoring_entry: 5870318,
  id: 24,
  is_current: true,
  is_next: false,
  is_previous: false,
  most_captained: 1,
  most_selected: 2,
  most_transferred_in: 1,
  most_vice_captained: 2,
  name: "Gameweek 24",
  top_element: 3,
  top_element_info: { id: 3, points: 13 },
  transfers_made: 8710540,
};

export const mockPlayers: Player[] = [
  {
    assists: 0,
    bonus: 0,
    bps: 48,
    chance_of_playing_next_round: 100,
    chance_of_playing_this_round: 100,
    clean_sheets: 0,
    code: 80201,
    corners_and_indirect_freekicks_order: null,
    corners_and_indirect_freekicks_text: "",
    cost_change_event: 0,
    cost_change_event_fall: 0,
    cost_change_start: -5,
    cost_change_start_fall: 5,
    creativity: "0.0",
    creativity_rank: 579,
    creativity_rank_type: 65,
    direct_freekicks_order: null,
    direct_freekicks_text: "",
    dreamteam_count: 0,
    element_type: 1,
    ep_next: "0.0",
    ep_this: "0.5",
    event_points: 0,
    first_name: "Bernd",
    form: "0.0",
    goals_conceded: 9,
    goals_scored: 0,
    ict_index: "7.9",
    ict_index_rank: 408,
    ict_index_rank_type: 29,
    id: 1,
    in_dreamteam: false,
    influence: "79.0",
    influence_rank: 347,
    influence_rank_type: 28,
    minutes: 270,
    news: "",
    news_added: new Date("2022-01-21T01:30:13.991200Z"),
    now_cost: 45,
    own_goals: 0,
    penalties_missed: 0,
    penalties_order: null,
    penalties_saved: 0,
    penalties_text: "",
    photo: "80201.jpg",
    points_per_game: "1.3",
    red_cards: 0,
    saves: 9,
    second_name: "Leno",
    selected_by_percent: "0.8",
    special: false,
    squad_number: null,
    status: "a",
    team: 1,
    team_code: 3,
    threat: "0.0",
    threat_rank: 560,
    threat_rank_type: 59,
    total_points: 4,
    transfers_in: 63447,
    transfers_in_event: 32,
    transfers_out: 186977,
    transfers_out_event: 41,
    value_form: "0.0",
    value_season: "0.9",
    web_name: "Leno",
    yellow_cards: 0,
  },
  {
    assists: 0,
    bonus: 0,
    bps: 0,
    chance_of_playing_next_round: 0,
    chance_of_playing_this_round: 0,
    clean_sheets: 0,
    code: 115918,
    corners_and_indirect_freekicks_order: null,
    corners_and_indirect_freekicks_text: "",
    cost_change_event: 0,
    cost_change_event_fall: 0,
    cost_change_start: 0,
    cost_change_start_fall: 0,
    creativity: "0.0",
    creativity_rank: 491,
    creativity_rank_type: 29,
    direct_freekicks_order: null,
    direct_freekicks_text: "",
    dreamteam_count: 0,
    element_type: 1,
    ep_next: "0.0",
    ep_this: "0.0",
    event_points: 0,
    first_name: "Rúnar Alex",
    form: "0.0",
    goals_conceded: 0,
    goals_scored: 0,
    ict_index: "0.0",
    ict_index_rank: 511,
    ict_index_rank_type: 53,
    id: 2,
    in_dreamteam: false,
    influence: "0.0",
    influence_rank: 508,
    influence_rank_type: 53,
    minutes: 0,
    news: "Joined OH Leuven on a season-long loan - Expected back 01 Jul",
    news_added: new Date("2021-08-31T22:00:09.069158Z"),
    now_cost: 40,
    own_goals: 0,
    penalties_missed: 0,
    penalties_order: null,
    penalties_saved: 0,
    penalties_text: "",
    photo: "115918.jpg",
    points_per_game: "0.0",
    red_cards: 0,
    saves: 0,
    second_name: "Rúnarsson",
    selected_by_percent: "0.6",
    special: false,
    squad_number: null,
    status: "u",
    team: 1,
    team_code: 3,
    threat: "0.0",
    threat_rank: 455,
    threat_rank_type: 19,
    total_points: 0,
    transfers_in: 19017,
    transfers_in_event: 0,
    transfers_out: 75886,
    transfers_out_event: 32,
    value_form: "0.0",
    value_season: "0.0",
    web_name: "Rúnarsson",
    yellow_cards: 0,
  },
  {
    assists: 0,
    bonus: 0,
    bps: 0,
    chance_of_playing_next_round: 0,
    chance_of_playing_this_round: 0,
    clean_sheets: 0,
    code: 47431,
    corners_and_indirect_freekicks_order: null,
    corners_and_indirect_freekicks_text: "",
    cost_change_event: 0,
    cost_change_event_fall: 0,
    cost_change_start: -2,
    cost_change_start_fall: 2,
    creativity: "0.0",
    creativity_rank: 696,
    creativity_rank_type: 286,
    direct_freekicks_order: null,
    direct_freekicks_text: "",
    dreamteam_count: 0,
    element_type: 3,
    ep_next: "0.0",
    ep_this: "0.0",
    event_points: 0,
    first_name: "Willian",
    form: "0.0",
    goals_conceded: 0,
    goals_scored: 0,
    ict_index: "0.0",
    ict_index_rank: 696,
    ict_index_rank_type: 286,
    id: 3,
    in_dreamteam: false,
    influence: "0.0",
    influence_rank: 696,
    influence_rank_type: 286,
    minutes: 0,
    news: "Transferred to Corinthians",
    news_added: new Date("2021-08-20T09:30:14.065783Z"),
    now_cost: 63,
    own_goals: 0,
    penalties_missed: 0,
    penalties_order: null,
    penalties_saved: 0,
    penalties_text: "",
    photo: "47431.jpg",
    points_per_game: "0.0",
    red_cards: 0,
    saves: 0,
    second_name: "Borges Da Silva",
    selected_by_percent: "0.1",
    special: false,
    squad_number: null,
    status: "u",
    team: 1,
    team_code: 3,
    threat: "0.0",
    threat_rank: 696,
    threat_rank_type: 286,
    total_points: 0,
    transfers_in: 914,
    transfers_in_event: 0,
    transfers_out: 20430,
    transfers_out_event: 2,
    value_form: "0.0",
    value_season: "0.0",
    web_name: "Willian",
    yellow_cards: 0,
  },
];
